source "http://rubygems.org"

gem "rails", "3.0.10"
gem 'mysql'

gem 'authlogic'
gem "bcrypt-ruby", :require => "bcrypt"
gem "jammit"

gem 'muck-engine' #, :path => "~/projects/muck-engine"
gem 'muck-resources'
gem 'muck-users', :path => "../"

group :test, :development do
  gem "ruby-debug", :platform => [:ruby_18]
  gem "ruby-debug19", :platform => [:ruby_19]
  gem "rspec-rails", ">=2.1.0"
  gem "cucumber-rails"
end

group :test do
  gem "autotest"
  gem "capybara", ">= 0.3.9"
  gem "shoulda"
  gem "factory_girl"
  gem "cucumber"
  gem "rcov"
  gem "rspec"
  gem "database_cleaner"
  gem "spork"
  gem "launchy"
end