source "http://rubygems.org"

gem "rails", "3.0.4"
gem 'mysql'

# gem 'authlogic'
# TODO this is temporary until the official authlogic gem is updated for rails 3
gem 'authlogic', :git => 'git://github.com/odorcicd/authlogic.git', :branch => 'rails3'
gem "bcrypt-ruby", :require => "bcrypt"

gem 'muck-engine', :path => "~/projects/muck-engine"
gem 'muck-users', :path => "../"

if RUBY_VERSION < '1.9'
  gem "ruby-debug"
end

group :test, :development do
  gem "rspec-rails"
  gem "cucumber-rails"
end

group :test do
  gem "autotest"
  gem "capybara", ">= 0.3.9"
  gem "shoulda"
  gem "factory_girl"
  gem "cucumber"
  gem "rcov"
  gem "rspec"
  gem "database_cleaner"
  gem "spork"
  gem "launchy"
end